import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guideSidebar: [
    "getting-started",
    {
      type: "category",
      label: "Guides",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
  ],
  apiSidebar: ["api-reference/index"],
};

export default sidebars;
